CREATE TABLE `product` (
  `Id` int(11) NOT NULL,
  `Name` varchar(256) DEFAULT NULL,
  `ProductCode` varchar(256) DEFAULT NULL,
  `Image_Price` varchar(256) DEFAULT NULL,
  `Image_Detail` text,
  `Image_Marketing` text,
  `Image_Produce` text,
  `DescriptionSummary` text,
  `DescriptionDetail` text,
  `Color` varchar(256) DEFAULT NULL,
  `MaterialId` int(11) DEFAULT NULL,
  `Material_subId` int(11) DEFAULT NULL,
  `CategoryId` int(11) DEFAULT NULL,
  `SupplierId` int(11) DEFAULT NULL,
  `Monopoly` int(11) DEFAULT NULL,
  `UpdateTime` datetime DEFAULT NULL,
  `Validity` date DEFAULT NULL,
  `Status` int(11) DEFAULT NULL,
  `Size` varchar(256) DEFAULT NULL,
  `Width` varchar(256) DEFAULT NULL,
  `Height` varchar(256) DEFAULT NULL,
  `Length` varchar(256) DEFAULT NULL,
  `Unit` varchar(256) DEFAULT NULL,
  `Quantity` varchar(256) DEFAULT NULL,
  `BoxOutQuantity` int(11) DEFAULT NULL,
  `BoxOutHeihgt` int(11) DEFAULT NULL,
  `BoxOutWidth` int(11) DEFAULT NULL,
  `BoxOutLength` int(11) DEFAULT NULL,
  `BoxInQuantity` int(11) DEFAULT NULL,
  `BoxInHeihgt` int(11) DEFAULT NULL,
  `BoxInWidth` int(11) DEFAULT NULL,
  `BoxInLength` int(11) DEFAULT NULL,
  `CBM` int(11) DEFAULT NULL,
  `QuantityOfBoxOut` int(11) DEFAULT NULL,
  `QuantityOfCBM` int(11) DEFAULT NULL,
  `QuantityOfContainer` int(11) DEFAULT NULL,
  `NetWeight` int(11) DEFAULT NULL,
  `GrossWeight` int(11) DEFAULT NULL,
  `Warning` text,
  `Note` text,
  `Price_Base` int(11) DEFAULT NULL,
  `Tolerant_Width` text,
  `Tolerant_Length` text,
  `Tolerant_Height` text,
  `Tolerant_Color` text,
  `Tolerant_weight` text,
  `UserUpload` varchar(256) DEFAULT NULL,
  `UserUpdate` varchar(256) DEFAULT NULL,
  `Lang` varchar(256) DEFAULT 'vi',
  `IsHide` int(11) DEFAULT '0',
  `PhotoDate` date DEFAULT NULL,
  `MarketingPrice` double DEFAULT NULL,
  `AlibabaDate` date DEFAULT NULL,
  `AlibabaLink` varchar(512) DEFAULT NULL,
  `WebsiteLink` varchar(512) DEFAULT NULL,
  `WebsiteDate` date DEFAULT NULL,
  `Segment` int(11) DEFAULT '0',
  `Tags` text,
  `MktName` varchar(256) NOT NULL,
  `MktCategory` varchar(256) NOT NULL,
  `MktShortDescription` text NOT NULL,
  `MktDescription` text NOT NULL,
  `MktColor` varchar(256) NOT NULL,
  `MktAccentColor` varchar(256) NOT NULL,
  `MtkShape` varchar(256) NOT NULL,
  `MktProductLine` varchar(256) NOT NULL,
  `ProductCode2` varchar(256) DEFAULT NULL,
  `SourceId` int(11) DEFAULT NULL,
  `Publish` int(11) DEFAULT '1',
  `RoomId` varchar(512) NOT NULL,
  `MaterialType` int(11) NOT NULL,
  `BuyerId` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
